#!/bin/bash

#************************************************************************
# Copyright (c) 2025 Tomatek Audio All rights reserved.
#************************************************************************

#####################################################################
#     Generates inline Faust objects for Raspberry Pi Circle        #
#           Thomas Hopman Tomatek Audio                             #
#           based on faust2api by Romain Michon                     #
#####################################################################

. faustpath
. faustoptflags
. usage.sh

# change if you want to get the log of what's happening
LOG="/dev/null"
#LOG="log"

# exit if a command fails
set -e

# global option variables

NVOICES="0"
#PACKAGENAME="0"
POLY2="0"
MIDI="0"
OSC="0"
NODOC="0"
EFFECT=""

echoHelp()
{
    usage faust2circle "[options] [Faust options] <file.dsp>"
    platform "Raspberry Pi"
    echo "Generates inline Faust objects for Raspberry Pi Circle"
    option
    option -midi "Enable MIDI control"
    option -osc "Enable OSC control (bare metal)"
    option "-nvoices <num>"
    option "-effect <effect.dsp>"
    option "Faust options"
    exit
}

if [ "$#" -eq 0 ]; then
    echo 'Please, provide a Faust file to process !'
    echo ''
    echoHelp
fi

createAPI ()
{
    #cp -r $FAUSTARCH/circle/fast_pow2.h $APIFOLDER
    cp -r $FAUSTARCH/circle/circleFaustDSP.h $APIFOLDER
    faust -i -a circle/circleFaustDSP.cpp $OPTIONS "$FILE" -o "$APIFOLDER/circleFaustDSP.cpp" || exit 1
    if [ "$POLY2" = "1" ]; then
        faust -i -cn effect -a minimal-effect.cpp $EFFECT | cat - "$APIFOLDER/circleFaustDSP.cpp" > temp && mv temp "$APIFOLDER/circleFaustDSP.cpp" || exit 1
        echo "#define POLY2 1" | cat - "$APIFOLDER/circleFaustDSP.cpp" > temp && mv temp "$APIFOLDER/circleFaustDSP.cpp"
    fi
    if [ "$NVOICES" -gt "0" ]; then
        echo "#define NVOICES $NVOICES" | cat - "$APIFOLDER/circleFaustDSP.cpp" > temp && mv temp "$APIFOLDER/circleFaustDSP.cpp"
    fi
    if [ "$MIDI" = "1" ]; then
        echo "#define MIDICTRL 1" | cat - "$APIFOLDER/circleFaustDSP.cpp" > temp && mv temp "$APIFOLDER/circleFaustDSP.cpp"
    fi
    if [ "$OSC" = "1" ]; then
        echo "#define OSCCTRL 1" | cat - "$APIFOLDER/circleFaustDSP.cpp" > temp && mv temp "$APIFOLDER/circleFaustDSP.cpp"
    fi
}

# dispatch command arguments
while [ $1 ]
do
    p=$1

    if [ $p = "-help" ] || [ $p = "-h" ]; then
        echoHelp
    elif [ "$PACKAGENAME" = "-1" ]; then
        PACKAGENAME="$p"
    elif [[ -f "$p" ]]; then
        FILE="$p"
    elif [ "$p" = "-effect" ]; then
        POLY2="1"
        shift
        EFFECT=$1
    elif [ "$p" = "-midi" ]; then
        MIDI="1"
    elif [ "$p" = "-osc" ]; then
        OSC="1"
    elif [ $p = "-nvoices" ]; then
        shift
        NVOICES=$1
    elif [ $p = "-package" ]; then
        PACKAGENAME="-1"
    elif [ ${p:0:1} = "-" ]; then
        OPTIONS="$OPTIONS $p"
    elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
        FILES="$FILES $p"
    else
        OPTIONS="$OPTIONS $p"
    fi

shift

done

###################################
# GENERATING API
###################################

APIFOLDER="${FILE%.*}-circle"

rm -r "$APIFOLDER" 2> /dev/null || true
mkdir "$APIFOLDER"

echo "Your $APIFOLDER.zip package is being created"
createAPI

###################################
# POST PROCESSING
###################################

ZIPOUT="$APIFOLDER.zip"

rm $ZIPOUT 2> /dev/null || true
zip -r $ZIPOUT $APIFOLDER > /dev/null || exit 1
rm -r $APIFOLDER || exit 1

# echos generated files for FaustWorks
echo "$ZIPOUT;"
